-- V1: esquema inicial de TicketHub (sección 7 del documento de alcance)

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL CHECK (role IN ('USER', 'AGENT', 'ADMIN')),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL
);

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(60)  NOT NULL UNIQUE,
    description VARCHAR(255),
    active      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE tickets (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio             VARCHAR(20)  NOT NULL UNIQUE,
    title             VARCHAR(120) NOT NULL,
    description       TEXT         NOT NULL,
    status            VARCHAR(20)  NOT NULL
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'CANCELLED')),
    priority          VARCHAR(20)  NOT NULL CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    solution          TEXT,
    created_by        BIGINT       NOT NULL REFERENCES users (id),
    assigned_to       BIGINT       REFERENCES users (id),
    category_id       BIGINT       NOT NULL REFERENCES categories (id),
    due_response_at   TIMESTAMPTZ,
    due_resolution_at TIMESTAMPTZ,
    resolved_at       TIMESTAMPTZ,
    closed_at         TIMESTAMPTZ,
    sla_breached      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_tickets_status ON tickets (status);
CREATE INDEX idx_tickets_created_by ON tickets (created_by);
CREATE INDEX idx_tickets_assigned_to ON tickets (assigned_to);
CREATE INDEX idx_tickets_created_at ON tickets (created_at);

CREATE TABLE comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id  BIGINT      NOT NULL REFERENCES tickets (id),
    author_id  BIGINT      NOT NULL REFERENCES users (id),
    body       TEXT        NOT NULL,
    internal   BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_comments_ticket ON comments (ticket_id);

CREATE TABLE attachments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id     BIGINT       NOT NULL REFERENCES tickets (id),
    comment_id    BIGINT       REFERENCES comments (id),
    uploaded_by   BIGINT       NOT NULL REFERENCES users (id),
    original_name VARCHAR(255) NOT NULL,
    storage_key   VARCHAR(255) NOT NULL UNIQUE,
    content_type  VARCHAR(100) NOT NULL,
    size_bytes    BIGINT       NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_attachments_ticket ON attachments (ticket_id);

CREATE TABLE ticket_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id  BIGINT       NOT NULL REFERENCES tickets (id),
    changed_by BIGINT       NOT NULL REFERENCES users (id),
    field      VARCHAR(30)  NOT NULL,
    old_value  VARCHAR(255),
    new_value  VARCHAR(255),
    changed_at TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_history_ticket ON ticket_history (ticket_id);

CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ  NOT NULL,
    used       BOOLEAN      NOT NULL DEFAULT FALSE
);
